### PR TITLE
#365 #345 regions vocab additions & fixes

### LINKED ISSUE #365: "Regions" drop-down should include AU states and territories
The "regions" drop-down select is a set of hard-coded entries, most of which are ISO countries.

SDS lists are specific to states and territories and use the regions property for this. Currently trying to upload a SDS list via the UI or API will fail if the region is a state, such as "NSW".

- [x]  get a list of distinct region values from old lists
- [x] create a JSON file and add to the code, similar to the existing countries list
- [x] ensure this JSON file is loaded at startup and regions list contains the new values

CC: @TaniaGLaity @adam-collins

### PR DESCRIPTION
**Pull request by nickdos**
#365 & #345

### CODE REVIEW

File: lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java [hunk 1]
```diff
@@ -546,35 +546,35 @@ private SpeciesListItem updateItem(
...
+        speciesListItem.getOrder(),
+        speciesListItem.getFamily(),
+        speciesListItem.getGenus(),
+        speciesListItem.getProperties(),
+        speciesListItem.getClassification(),
+        speciesList.getIsPrivate() != null ? speciesList.getIsPrivate() : false,
+        speciesList.getIsAuthoritative() != null ? speciesList.getIsAuthoritative() : false,
+        speciesList.getIsBIE() != null ? speciesList.getIsBIE() : false,
+        speciesList.getIsSDS() != null ? speciesList.getIsSDS() : false,
+        StringUtils.isNotEmpty(speciesList.getRegion()) || StringUtils.isNotEmpty(speciesList.getWkt()),
```
Comment (nickdos) [inline lists-service/src/main/java/au/org/ala/listsapi/controller/GraphQLController.java:570]: #345 fix

File: lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java [hunk 2]
```diff
@@ -175,12 +176,10 @@ private SpeciesListIndex listItemToIndex(SpeciesList speciesList, SpeciesListIte
...
                     speciesListItem.getClassification(),
                     speciesList.getIsPrivate() != null ? speciesList.getIsPrivate() : false,
-                    speciesList.getIsAuthoritative() != null
-                            ? speciesList.getIsAuthoritative()
-                            : false,
+                    speciesList.getIsAuthoritative() != null ? speciesList.getIsAuthoritative() : false,
                     speciesList.getIsBIE() != null ? speciesList.getIsBIE() : false,
                     speciesList.getIsSDS() != null ? speciesList.getIsSDS() : false,
-                    speciesList.getRegion() != null || speciesList.getWkt() != null,
+                    StringUtils.isNotEmpty(speciesList.getRegion()) || StringUtils.isNotEmpty(speciesList.getWkt()),
```
Comment (nickdos) [inline lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java:182]: #345 fix

File: lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java [hunk 3]
```diff
@@ -219,10 +218,11 @@ public void reindex(String speciesListID) {
       if (!speciesListItems.isEmpty()) {
         List<IndexQuery> updateList = new ArrayList<>();
         for (SpeciesListItem item : speciesListItems) {
+          SpeciesListIndex indexItem = listItemToIndex(speciesList, item);
```
Comment (nickdos) [inline lists-service/src/main/java/au/org/ala/listsapi/service/TaxonService.java:221]: simplified for debugging and code clarity

File: lists-service/src/main/java/au/org/ala/listsapi/service/ValidationService.java [hunk 4]
```diff
@@ -44,26 +49,38 @@ private void setConstraintsByKey(ConstraintType constraintType, List<ConstraintL
...
+      // Handle exceptions appropriately (e.g., logging, re-throwing a custom exception)
+      throw new RuntimeException("Failed to read or parse constraints file from: " + constraintsFile.getDescription(), e);
+    }
 
-      setConstraintsByKey(ConstraintType.region, countries);
-    } catch (Exception ex) {
-      log.error("Error loading country constraints from userdetails", ex);
+    // TODO: Review whether this should be removed or not. No lists in the legacy lists app
+    // use coutries apart from Australia and New Zealand. So suggesting this be removed.
+    if (userDetailsCountriesEnabled) {
```
Comment (nickdos) [inline lists-service/src/main/java/au/org/ala/listsapi/service/ValidationService.java:66]: Thoughts on TODO comment above?

Comment (adam-collins) [reply lists-service/src/main/java/au/org/ala/listsapi/service/ValidationService.java:66]: Remove it.

**Review by adam-collins — APPROVED** [review]
If we want users to use the region field it must be unconstrained (backwards compatible), if not flexible. See prod lists, though I only see 4 meaningful values we would never add to the constraints.json. 

If we do not want people to use the regions field it should be restricted to authoritative lists only.

In a perfect world a better solution would be implemented, but that is hard. Both the biocollect and spatial solutions are complex.
